version: "3"
services:
  groundstation:
    image: inf3995-101-groundstation
    build: groundstation
    ports:
      - "8000:8000"
  rover:
    image: inf3995-101-rover
    build: rover
  sim:
    image: inf3995-101-sim
    build: sim
    ports:
      - "5901:5901"
