version: "3"
services:
  groundstation:
    image: inf3995-101-groundstation
    build: groundstation
    network_mode: host
  rover:
    image: inf3995-101-rover
    build: rover

  cognifly:
    image: inf3995-101-cognifly
    build: cognifly

  sim:
    image: inf3995-101-sim
    build: sim
    ports:
      - "5901:5901"
